# code referenced from https://www.marvinschmitt.com/blog/website-tutorial-quarto/  

# website settings
website:
  title: "Julia V.E. Kim"                             
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # sub-pages
    left:
      - text: "Research Projects"
        href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    #  social media handles
    right:
      - icon: github 
        href: https://github.com/julia-ve-kim 
      - icon: instagram 
        href: https://www.instagram.com/julia.ve.turner/ 
      - icon: linkedin
        href: https://www.linkedin.com/in/julia-kim-b6224b205/ 
      - icon: envelope
        aria-label: email
        href: "mailto:mail.juliaym.kim@mail.utoronto.ca"  
  
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Julia Kim. All rights reserved.</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">Design and code supported by Martin Schmitt (2023).</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/julia-ve-kim/personal_quarto_webpage/blob/main/README.md">Images courtesy of Encyclopedia Britannica and NEDS.</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - cosmo 
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true